/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuardhealthySystem;

import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Viccine extends javax.swing.JFrame {

    /**
     * Creates new form ChildTable
     */
    public Viccine() {
        initComponents();
        addchildColumn();
        displaydata();
    }
    String url = "jdbc:mysql://localhost:3306/Guard_healthy_System";
    String user = "root"; 
    String password = "";  
      DefaultTableModel tmodel = new DefaultTableModel();

    // Combo box model for medicine names
    DefaultComboBoxModel<String> medicineComboBoxModel = new DefaultComboBoxModel<>();
     public void addchildColumn() {
        tmodel.addColumn("Vaccine ID");
        tmodel.addColumn("Name Description");
        tmodel.addColumn("Reccomanded Age");
        Childtabledata.setModel(tmodel);
    }
public void displaydata() {
        tmodel.setRowCount(0);
        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            String selectQuery = "SELECT * FROM vaccine";
            try (PreparedStatement preparedStatement = connection.prepareStatement(selectQuery)) {
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    while (resultSet.next()) {
                        tmodel.addRow(new Object[]{
                                resultSet.getString("vaccineid"),
                                resultSet.getString("description"),
                                resultSet.getString("age"),
                        });
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Childtabledata = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ViccineSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        serachrecord = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        viccineid = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        RegisterReccord = new javax.swing.JButton();
        Updaterecord = new javax.swing.JButton();
        Deleterecord = new javax.swing.JButton();
        Clearfunction = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Childtabledata.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Childtabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Childtabledata.setRowHeight(40);
        jScrollPane1.setViewportView(Childtabledata);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setText("Name Description");

        ViccineSearch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ViccineSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViccineSearchActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel5.setText("Provide ID");

        serachrecord.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        serachrecord.setText("Seach");
        serachrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachrecordActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel6.setText("Viccine ID");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel7.setText("Recommended age");

        age.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        viccineid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        description.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        RegisterReccord.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RegisterReccord.setText("Register");
        RegisterReccord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterReccordActionPerformed(evt);
            }
        });

        Updaterecord.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Updaterecord.setText("Update");
        Updaterecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdaterecordActionPerformed(evt);
            }
        });

        Deleterecord.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Deleterecord.setText("Delete");
        Deleterecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleterecordActionPerformed(evt);
            }
        });

        Clearfunction.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Clearfunction.setText("Clear");
        Clearfunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearfunctionActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("<<Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RegisterReccord, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Updaterecord, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Deleterecord, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(Clearfunction, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(ViccineSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(serachrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viccineid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel6)
                                .addGap(70, 70, 70)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(description, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2)
                                .addGap(66, 66, 66)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel7)))
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(499, 499, 499))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viccineid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterReccord, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Updaterecord, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deleterecord, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViccineSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(serachrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clearfunction))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1241, 798));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void serachrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachrecordActionPerformed
        if(ViccineSearch.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Search Field First","Error", JOptionPane.ERROR_MESSAGE);
         }else{
        try {
            Connection connection = DriverManager.getConnection(url, user, password);
            String seleQuery = "SELECT * FROM Vaccine where vaccineid=?";
            PreparedStatement preparedStatement = connection.prepareStatement(seleQuery);
            preparedStatement.setString(1, ViccineSearch.getText());
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()) {
                viccineid.setText(resultSet.getString("vaccineid"));
                description.setText(resultSet.getString("description"));
                age.setText(resultSet.getString("age"));

            }else{
                JOptionPane.showMessageDialog(null, " Vaccine ID not Exist ", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_serachrecordActionPerformed

    private void RegisterReccordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterReccordActionPerformed
         if(viccineid.getText().isEmpty()||description.getText().isEmpty()||age.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill all Fields","Error", JOptionPane.ERROR_MESSAGE);
         }else{
        try{
            Connection connection = DriverManager.getConnection(url, user, password);
            String insertQuery = "INSERT INTO Vaccine  VALUES (?, ?, ?)";
            PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
            preparedStatement.setString(1, viccineid.getText());
            preparedStatement.setString(2, description.getText());
            preparedStatement.setString(3, age.getText());

            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Registered successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                displaydata();
            } else {
                JOptionPane.showMessageDialog(null, "Failed to register", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Unexpected error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
         }

    }//GEN-LAST:event_RegisterReccordActionPerformed

    private void UpdaterecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdaterecordActionPerformed
        if(ViccineSearch.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Search Field First","Error", JOptionPane.ERROR_MESSAGE);
         }else if(viccineid.getText().isEmpty()||description.getText().isEmpty()||age.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill all Fields","Error", JOptionPane.ERROR_MESSAGE);
         }else{
        try {
            Connection connection = DriverManager.getConnection(url, user, password);
            String insertQuery = "UPDATE vaccine SET description=?,age=? WHERE vaccineid=?";
            PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
            preparedStatement.setString(1, description.getText());
            preparedStatement.setString(2, age.getText());
            preparedStatement.setString(3, ViccineSearch.getText());
            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                displaydata();
            } else {
                JOptionPane.showMessageDialog(null, "Updated fail", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
       }

    }//GEN-LAST:event_UpdaterecordActionPerformed

    private void DeleterecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleterecordActionPerformed
        if(ViccineSearch.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Search Field First","Error", JOptionPane.ERROR_MESSAGE);
         }else{
        try {
            Connection connection = DriverManager.getConnection(url, user, password);
            String insertQuery = "DELETE FROM Vaccine Where vaccineid=?";
            PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
            preparedStatement.setString(1, ViccineSearch.getText());

            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Delete successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                displaydata();
            } else {
                JOptionPane.showMessageDialog(null, "Delete fail", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_DeleterecordActionPerformed

    private void ClearfunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearfunctionActionPerformed
       viccineid.setText("");
       description.setText("");
       age.setText("");
    }//GEN-LAST:event_ClearfunctionActionPerformed

    private void ViccineSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViccineSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViccineSearchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new Dashbord().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viccine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Childtabledata;
    private javax.swing.JButton Clearfunction;
    private javax.swing.JButton Deleterecord;
    private javax.swing.JButton RegisterReccord;
    private javax.swing.JButton Updaterecord;
    private javax.swing.JTextField ViccineSearch;
    private javax.swing.JTextField age;
    private javax.swing.JTextField description;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton serachrecord;
    private javax.swing.JTextField viccineid;
    // End of variables declaration//GEN-END:variables
}
